<a href="https://colab.research.google.com/github/ephemerno/testing/blob/master/Weather%20Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
data = pd.read_csv('/content/1. Weather Data(1).csv')

In [ ]:
data

In [ ]:
data.head()

In [ ]:
data.shape

In [ ]:
data.index

In [ ]:
data.columns

In [ ]:
data.dtypes

In [ ]:
data['Weather'].unique()

In [ ]:
data.nunique()

In [ ]:
data.count()

In [ ]:
data['Weather'].value_counts()

In [ ]:
data.info()

In [ ]:
data.head(2)

In [ ]:
data.nunique()

In [ ]:
data['Wind Speed_km/h'].nunique()

In [ ]:
data['Wind Speed_km/h'].unique()

**Find the number of times when the "Weather is exactly Clear**

In [ ]:
data.head(2)

In [ ]:
#value_counts()
data.Weather.value_counts()

In [ ]:
#data.head(2)
data[data.Weather == 'Clear']

In [ ]:
#data.head(2)
data.groupby('Weather').get_group('Clear')

**Find the number of times when the 'Wind Speed was exactly 4 km/h**

In [6]:
data.head(2)
data[data['Wind Speed_km/h'] == 4]

             Date/Time  Temp_C  ...  Press_kPa       Weather
0        1/1/2012 0:00    -1.8  ...     101.24           Fog
1        1/1/2012 1:00    -1.8  ...     101.24           Fog
96       1/5/2012 0:00    -8.8  ...     100.32          Snow
101      1/5/2012 5:00    -7.0  ...     100.19          Snow
146      1/7/2012 2:00    -8.1  ...     100.15        Cloudy
...                ...     ...  ...        ...           ...
8768   12/31/2012 8:00    -8.6  ...     101.14  Snow Showers
8769   12/31/2012 9:00    -8.1  ...     101.09          Snow
8770  12/31/2012 10:00    -7.4  ...     101.05      Snow,Fog
8772  12/31/2012 12:00    -5.8  ...     100.78          Snow
8773  12/31/2012 13:00    -4.6  ...     100.63          Snow

[474 rows x 8 columns]

**Find out all the Null Values in the data**

In [9]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

**Rename the column name "Weater" of the dataframe to "Weather Condition"**

In [12]:
#data.head(2)
data.rename(columns = {'Weather' : 'Weather Condition'}, inplace = True)

In [13]:
data.head()

       Date/Time  Temp_C  ...  Press_kPa     Weather Condition
0  1/1/2012 0:00    -1.8  ...     101.24                   Fog
1  1/1/2012 1:00    -1.8  ...     101.24                   Fog
2  1/1/2012 2:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  1/1/2012 3:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  1/1/2012 4:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

**What is the mean 'Visibility'?**

In [15]:
data.head(2)
data.Visibility_km.mean()

27.66444672131151

**What is the Standart Deviation of 'Pressure' in this data?**

In [16]:
data.Press_kPa.std()

0.8440047459486474

**Whats is the Variance of 'Relative Humidity' in this data?**

In [18]:
data['Rel Hum_%'].var()

286.2485501984998

**Find all instances when 'Snow' was recorded**

In [20]:
#value_counts()
#data.head(2)
data['Weather Condition'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Moderate Snow                                 4
Freezing Rain,Fog                             4
Snow Showers,Fog                              4
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Freezing Drizzle,Haze                         3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Rain,Haze                                     3
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Freezing Rain,Haze                            2
Moderate Rain,Fog                             1
Snow Pellets                                  1
Thunderstorms,Heavy Rain Showers              1
Rain,Ice Pellets                              1
Rain,Snow,Fog                                 1
Drizzle,Ice Pellets,Fog                       1
Rain Showers,Fog                              1
Rain,Snow Grains                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Freezing Rain,Snow Grains                     1
Freezing Rain,Ice Pellets,Fog                 1
Thunderstorms,Rain,Fog                        1
Name: Weather Condition, dtype: int64

In [21]:
#filtering
data[data['Weather Condition'] == 'Snow']

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
55       1/3/2012 7:00   -14.0  ...     100.95               Snow
84      1/4/2012 12:00   -13.7  ...     101.25               Snow
86      1/4/2012 14:00   -11.3  ...     100.97               Snow
87      1/4/2012 15:00   -10.2  ...     100.89               Snow
88      1/4/2012 16:00    -9.4  ...     100.79               Snow
...                ...     ...  ...        ...                ...
8779  12/31/2012 19:00     0.1  ...     100.13               Snow
8780  12/31/2012 20:00     0.2  ...     100.03               Snow
8781  12/31/2012 21:00    -0.5  ...      99.95               Snow
8782  12/31/2012 22:00    -0.2  ...      99.91               Snow
8783  12/31/2012 23:00     0.0  ...      99.89               Snow

[390 rows x 8 columns]

In [25]:
#str.contains
data[data['Weather Condition'].str.contains('Snow')].tail(50)

             Date/Time  Temp_C  ...  Press_kPa      Weather Condition
8680  12/27/2012 16:00    -4.5  ...     100.44      Snow,Blowing Snow
8681  12/27/2012 17:00    -4.2  ...     100.47      Snow,Blowing Snow
8682  12/27/2012 18:00    -4.0  ...     100.49      Snow,Blowing Snow
8683  12/27/2012 19:00    -3.9  ...     100.52      Snow,Blowing Snow
8684  12/27/2012 20:00    -3.7  ...     100.58                   Snow
8685  12/27/2012 21:00    -3.7  ...     100.62  Freezing Drizzle,Snow
8686  12/27/2012 22:00    -3.8  ...     100.65  Freezing Drizzle,Snow
8687  12/27/2012 23:00    -4.0  ...     100.70                   Snow
8688   12/28/2012 0:00    -4.2  ...     100.78  Freezing Drizzle,Snow
8689   12/28/2012 1:00    -4.4  ...     100.83  Freezing Drizzle,Snow
8690   12/28/2012 2:00    -4.3  ...     100.93  Freezing Drizzle,Snow
8691   12/28/2012 3:00    -4.6  ...     101.01                   Snow
8692   12/28/2012 4:00    -4.9  ...     101.00                   Snow
8723  12/29/2012 11:00   -10.9  ...     101.09       Snow Showers,Fog
8724  12/29/2012 12:00   -10.5  ...     100.93       Snow Showers,Fog
8725  12/29/2012 13:00   -10.0  ...     100.63       Snow Showers,Fog
8726  12/29/2012 14:00    -9.3  ...     100.60               Snow,Fog
8727  12/29/2012 15:00    -8.8  ...     100.55               Snow,Fog
8728  12/29/2012 16:00    -8.5  ...     100.49               Snow,Fog
8729  12/29/2012 17:00    -9.0  ...     100.46               Snow,Fog
8730  12/29/2012 18:00    -9.3  ...     100.38               Snow,Fog
8731  12/29/2012 19:00    -9.5  ...     100.33               Snow,Fog
8732  12/29/2012 20:00    -9.7  ...     100.25               Snow,Fog
8733  12/29/2012 21:00    -9.8  ...     100.24               Snow,Fog
8734  12/29/2012 22:00   -10.1  ...     100.20               Snow,Fog
8735  12/29/2012 23:00   -10.0  ...     100.19               Snow,Fog
8736   12/30/2012 0:00    -9.6  ...     100.23               Snow,Fog
8737   12/30/2012 1:00    -9.4  ...     100.22               Snow,Fog
8738   12/30/2012 2:00    -9.3  ...     100.28               Snow,Fog
8739   12/30/2012 3:00    -9.1  ...     100.30               Snow,Fog
8740   12/30/2012 4:00    -9.3  ...     100.28               Snow,Fog
8741   12/30/2012 5:00    -9.1  ...     100.32               Snow,Fog
8742   12/30/2012 6:00    -9.3  ...     100.39               Snow,Fog
8767   12/31/2012 7:00    -9.3  ...     101.19           Snow Showers
8768   12/31/2012 8:00    -8.6  ...     101.14           Snow Showers
8769   12/31/2012 9:00    -8.1  ...     101.09                   Snow
8770  12/31/2012 10:00    -7.4  ...     101.05               Snow,Fog
8771  12/31/2012 11:00    -6.7  ...     100.93                   Snow
8772  12/31/2012 12:00    -5.8  ...     100.78                   Snow
8773  12/31/2012 13:00    -4.6  ...     100.63                   Snow
8774  12/31/2012 14:00    -3.4  ...     100.57                   Snow
8775  12/31/2012 15:00    -2.3  ...     100.47                   Snow
8776  12/31/2012 16:00    -1.4  ...     100.40                   Snow
8777  12/31/2012 17:00    -1.1  ...     100.30                   Snow
8778  12/31/2012 18:00    -1.3  ...     100.19                   Snow
8779  12/31/2012 19:00     0.1  ...     100.13                   Snow
8780  12/31/2012 20:00     0.2  ...     100.03                   Snow
8781  12/31/2012 21:00    -0.5  ...      99.95                   Snow
8782  12/31/2012 22:00    -0.2  ...      99.91                   Snow
8783  12/31/2012 23:00     0.0  ...      99.89                   Snow

[50 rows x 8 columns]

**Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'**

In [ ]:
data.head(2)

In [29]:
data[(data['Wind Speed_km/h'] > 24) & (data['Visibility_km'] == 25)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
23      1/1/2012 23:00     5.3  ...      99.31             Cloudy
24       1/2/2012 0:00     5.2  ...      99.26       Rain Showers
25       1/2/2012 1:00     4.6  ...      99.26             Cloudy
26       1/2/2012 2:00     3.9  ...      99.26      Mostly Cloudy
27       1/2/2012 3:00     3.7  ...      99.30      Mostly Cloudy
...                ...     ...  ...        ...                ...
8705  12/28/2012 17:00    -8.6  ...     101.34       Mainly Clear
8753  12/30/2012 17:00   -12.1  ...     101.26       Mainly Clear
8755  12/30/2012 19:00   -13.4  ...     101.47       Mainly Clear
8759  12/30/2012 23:00   -12.1  ...     101.52      Mostly Cloudy
8760   12/31/2012 0:00   -11.1  ...     101.51             Cloudy

[308 rows x 8 columns]

**What is the Mean value of each column against each 'Weather Condition'?**

In [31]:
data.head(2)
data.groupby('Weather Condition').mean()

                                            Temp_C  ...   Press_kPa
Weather Condition                                   ...
Clear                                     6.825716  ...  101.587443
Cloudy                                    7.970544  ...  100.911441
Drizzle                                   7.353659  ...  100.435366
Drizzle,Fog                               8.067500  ...  100.786625
Drizzle,Ice Pellets,Fog                   0.400000  ...  100.790000
Drizzle,Snow                              1.050000  ...  100.890000
Drizzle,Snow,Fog                          0.693333  ...   99.281333
Fog                                       4.303333  ...  101.184067
Freezing Drizzle                         -5.657143  ...  100.202857
Freezing Drizzle,Fog                     -2.533333  ...  100.441667
Freezing Drizzle,Haze                    -5.433333  ...  100.316667
Freezing Drizzle,Snow                    -5.109091  ...  100.520909
Freezing Fog                             -7.575000  ...  102.320000
Freezing Rain                            -3.885714  ...   99.647143
Freezing Rain,Fog                        -2.225000  ...   99.945000
Freezing Rain,Haze                       -4.900000  ...  100.375000
Freezing Rain,Ice Pellets,Fog            -2.600000  ...  100.950000
Freezing Rain,Snow Grains                -5.000000  ...   98.560000
Haze                                     -0.200000  ...  101.482500
Mainly Clear                             12.558927  ...  101.248832
Moderate Rain,Fog                         1.700000  ...   99.980000
Moderate Snow                            -5.525000  ...  100.275000
Moderate Snow,Blowing Snow               -5.450000  ...  100.570000
Mostly Cloudy                            10.574287  ...  101.025288
Rain                                      9.786275  ...  100.233333
Rain Showers                             13.722340  ...  100.404043
Rain Showers,Fog                         12.800000  ...   99.830000
Rain Showers,Snow Showers                 2.150000  ...  101.100000
Rain,Fog                                  8.273276  ...  100.500862
Rain,Haze                                 4.633333  ...  100.540000
Rain,Ice Pellets                          0.600000  ...  100.120000
Rain,Snow                                 1.055556  ...   99.951111
Rain,Snow Grains                          1.900000  ...  100.600000
Rain,Snow,Fog                             0.800000  ...  100.730000
Rain,Snow,Ice Pellets                     1.100000  ...  100.105000
Snow                                     -4.524103  ...  100.536103
Snow Pellets                              0.700000  ...   99.700000
Snow Showers                             -3.506667  ...  100.963500
Snow Showers,Fog                        -10.675000  ...  101.292500
Snow,Blowing Snow                        -5.410526  ...   99.704737
Snow,Fog                                 -5.075676  ...  100.688649
Snow,Haze                                -4.020000  ...  100.782000
Snow,Ice Pellets                         -1.883333  ...  100.548333
Thunderstorms                            24.150000  ...  100.230000
Thunderstorms,Heavy Rain Showers         10.900000  ...  100.260000
Thunderstorms,Moderate Rain Showers,Fog  19.600000  ...  100.010000
Thunderstorms,Rain                       20.433333  ...  100.420000
Thunderstorms,Rain Showers               20.037500  ...  100.233750
Thunderstorms,Rain Showers,Fog           21.600000  ...  100.063333
Thunderstorms,Rain,Fog                   20.600000  ...  100.080000

[50 rows x 6 columns]

**What is the Minimum & Maximum value of each column against each 'Weather Condition'**

In [ ]:
data.groupby('Weather Condition').max()

In [ ]:
data.groupby('Weather Condition').min()

**Show all the Records where Weather Condition is Fog**

In [34]:
data[data['Weather Condition'] == 'Fog']

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
0        1/1/2012 0:00    -1.8  ...     101.24                Fog
1        1/1/2012 1:00    -1.8  ...     101.24                Fog
4        1/1/2012 4:00    -1.5  ...     101.23                Fog
5        1/1/2012 5:00    -1.4  ...     101.27                Fog
6        1/1/2012 6:00    -1.5  ...     101.29                Fog
...                ...     ...  ...        ...                ...
8716   12/29/2012 4:00   -16.0  ...     101.25                Fog
8717   12/29/2012 5:00   -14.8  ...     101.25                Fog
8718   12/29/2012 6:00   -13.8  ...     101.25                Fog
8719   12/29/2012 7:00   -14.8  ...     101.22                Fog
8722  12/29/2012 10:00   -12.0  ...     101.15                Fog

[150 rows x 8 columns]

**Find all instances when 'Weather is Clear' or 'Visibility is above 40'**

In [37]:
data[(data['Weather Condition'] == 'Clear') |(data['Visibility_km'] > 40)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
67      1/3/2012 19:00   -16.9  ...     101.74              Clear
106     1/5/2012 10:00    -6.0  ...     100.45       Mainly Clear
107     1/5/2012 11:00    -5.6  ...     100.41       Mainly Clear
108     1/5/2012 12:00    -4.7  ...     100.38       Mainly Clear
109     1/5/2012 13:00    -4.4  ...     100.40       Mainly Clear
...                ...     ...  ...        ...                ...
8749  12/30/2012 13:00   -12.4  ...     100.92      Mostly Cloudy
8750  12/30/2012 14:00   -11.8  ...     100.96       Mainly Clear
8751  12/30/2012 15:00   -11.3  ...     101.05       Mainly Clear
8752  12/30/2012 16:00   -11.4  ...     101.15       Mainly Clear
8756  12/30/2012 20:00   -13.8  ...     101.52              Clear

[3027 rows x 8 columns]

**Find all instances when :**

Find all instances when:
A. 'Weather is Clear' and 'Relative Humidity' is greater than 50'
or
B. 'Visibility is above 40'

In [39]:
data.head(2)
data[(data['Weather Condition'] == 'Clear') & (data['Rel Hum_%'] > 50) | (data['Visibility_km'] > 40)]

             Date/Time  Temp_C  ...  Press_kPa  Weather Condition
106     1/5/2012 10:00    -6.0  ...     100.45       Mainly Clear
107     1/5/2012 11:00    -5.6  ...     100.41       Mainly Clear
108     1/5/2012 12:00    -4.7  ...     100.38       Mainly Clear
109     1/5/2012 13:00    -4.4  ...     100.40       Mainly Clear
110     1/5/2012 14:00    -5.1  ...     100.46       Mainly Clear
...                ...     ...  ...        ...                ...
8749  12/30/2012 13:00   -12.4  ...     100.92      Mostly Cloudy
8750  12/30/2012 14:00   -11.8  ...     100.96       Mainly Clear
8751  12/30/2012 15:00   -11.3  ...     101.05       Mainly Clear
8752  12/30/2012 16:00   -11.4  ...     101.15       Mainly Clear
8756  12/30/2012 20:00   -13.8  ...     101.52              Clear

[2921 rows x 8 columns]